// Code generated by protoc-gen-go.
// source: driver.proto
// DO NOT EDIT!

/*
Package driver is a generated protocol buffer package.

It is generated from these files:
	driver.proto
	runner.proto

It has these top-level messages:
	TypeRequest
	TypeReply
	RunRequest
	RunReply
	MessagesRequest
	MessagesReply
	SupportedRunTypesRequest
	SupportedRunTypesReply
*/
package driver

import proto "github.com/antha-lang/antha/bvendor/github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TypeRequest struct {
}

func (m *TypeRequest) Reset()                    { *m = TypeRequest{} }
func (m *TypeRequest) String() string            { return proto.CompactTextString(m) }
func (*TypeRequest) ProtoMessage()               {}
func (*TypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TypeReply struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *TypeReply) Reset()                    { *m = TypeReply{} }
func (m *TypeReply) String() string            { return proto.CompactTextString(m) }
func (*TypeReply) ProtoMessage()               {}
func (*TypeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*TypeRequest)(nil), "driver.TypeRequest")
	proto.RegisterType((*TypeReply)(nil), "driver.TypeReply")
}

func init() { proto.RegisterFile("driver.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 86 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x29, 0xca, 0x2c,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x78, 0xb9, 0xb8,
	0x43, 0x2a, 0x0b, 0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x94, 0xe4, 0xb9, 0x38, 0x21,
	0xdc, 0x82, 0x9c, 0x4a, 0x21, 0x21, 0x2e, 0x96, 0x12, 0x20, 0x47, 0x82, 0x51, 0x81, 0x51, 0x83,
	0x33, 0x08, 0xcc, 0x4e, 0x62, 0x03, 0x6b, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xf5,
	0x76, 0xb4, 0x4e, 0x00, 0x00, 0x00,
}
