{
    "Parameters": {
        "AliquotParams": {
            "NumberofAliquots": 4,
            "OutPlatetype": "eppendorfrack425_1.5ml",
            "Solution": "water",
            "SolutionVolume": "100ul",
            "VolumePerAliquot": "25ul"
        }
    }
}
