// Code generated by protoc-gen-go.
// source: github.com/antha-lang/antha/driver/antha_driver_v1/driver.proto
// DO NOT EDIT!

/*
Package antha_driver_v1 is a generated protocol buffer package.

It is generated from these files:
	github.com/antha-lang/antha/driver/antha_driver_v1/driver.proto

It has these top-level messages:
	TypeRequest
	TypeReply
	HttpHeader
	HttpCall
*/
package antha_driver_v1

import proto "github.com/antha-lang/antha/bvendor/github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "github.com/antha-lang/antha/bvendor/golang.org/x/net/context"
	grpc "github.com/antha-lang/antha/bvendor/google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type TypeRequest struct {
}

func (m *TypeRequest) Reset()                    { *m = TypeRequest{} }
func (m *TypeRequest) String() string            { return proto.CompactTextString(m) }
func (*TypeRequest) ProtoMessage()               {}
func (*TypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TypeReply struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *TypeReply) Reset()                    { *m = TypeReply{} }
func (m *TypeReply) String() string            { return proto.CompactTextString(m) }
func (*TypeReply) ProtoMessage()               {}
func (*TypeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type HttpHeader struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *HttpHeader) Reset()                    { *m = HttpHeader{} }
func (m *HttpHeader) String() string            { return proto.CompactTextString(m) }
func (*HttpHeader) ProtoMessage()               {}
func (*HttpHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Remote Http call
type HttpCall struct {
	Url     string        `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Method  string        `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`
	Body    []byte        `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Headers []*HttpHeader `protobuf:"bytes,4,rep,name=headers" json:"headers,omitempty"`
}

func (m *HttpCall) Reset()                    { *m = HttpCall{} }
func (m *HttpCall) String() string            { return proto.CompactTextString(m) }
func (*HttpCall) ProtoMessage()               {}
func (*HttpCall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HttpCall) GetHeaders() []*HttpHeader {
	if m != nil {
		return m.Headers
	}
	return nil
}

func init() {
	proto.RegisterType((*TypeRequest)(nil), "antha.driver.v1.TypeRequest")
	proto.RegisterType((*TypeReply)(nil), "antha.driver.v1.TypeReply")
	proto.RegisterType((*HttpHeader)(nil), "antha.driver.v1.HttpHeader")
	proto.RegisterType((*HttpCall)(nil), "antha.driver.v1.HttpCall")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Driver service

type DriverClient interface {
	DriverType(ctx context.Context, in *TypeRequest, opts ...grpc.CallOption) (*TypeReply, error)
}

type driverClient struct {
	cc *grpc.ClientConn
}

func NewDriverClient(cc *grpc.ClientConn) DriverClient {
	return &driverClient{cc}
}

func (c *driverClient) DriverType(ctx context.Context, in *TypeRequest, opts ...grpc.CallOption) (*TypeReply, error) {
	out := new(TypeReply)
	err := grpc.Invoke(ctx, "/antha.driver.v1.Driver/DriverType", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Driver service

type DriverServer interface {
	DriverType(context.Context, *TypeRequest) (*TypeReply, error)
}

func RegisterDriverServer(s *grpc.Server, srv DriverServer) {
	s.RegisterService(&_Driver_serviceDesc, srv)
}

func _Driver_DriverType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(DriverServer).DriverType(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Driver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "antha.driver.v1.Driver",
	HandlerType: (*DriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DriverType",
			Handler:    _Driver_DriverType_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xa9, 0xa9, 0xd1, 0x4e, 0x15, 0x65, 0x10, 0x09, 0x55, 0xb0, 0xe4, 0xd4, 0x8b, 0x5b,
	0x5a, 0xd1, 0xab, 0x07, 0x45, 0x7a, 0x94, 0xe0, 0xbd, 0x6c, 0xcc, 0xd2, 0x14, 0x36, 0xd9, 0xb8,
	0x9d, 0x2c, 0xe4, 0xe4, 0xbf, 0x6e, 0xf6, 0xc3, 0x0f, 0x14, 0x6f, 0xef, 0xf7, 0xe6, 0xbd, 0x64,
	0x67, 0xe0, 0x7e, 0xb3, 0xa5, 0xb2, 0xcd, 0xd9, 0xab, 0xaa, 0xe6, 0xbc, 0xa6, 0x92, 0x5f, 0x4b,
	0x5e, 0x6f, 0xbc, 0x9c, 0x17, 0x7a, 0x6b, 0x84, 0xf6, 0xb0, 0xf6, 0xb0, 0x36, 0x8b, 0x60, 0xb3,
	0x46, 0x2b, 0x52, 0x78, 0xe2, 0xa6, 0x2c, 0x78, 0x66, 0x91, 0x1e, 0xc3, 0xf8, 0xa5, 0x6b, 0x44,
	0x26, 0xde, 0x5a, 0xb1, 0xa3, 0xf4, 0x0a, 0x46, 0x1e, 0x1b, 0xd9, 0x21, 0xc2, 0x90, 0x7a, 0x48,
	0x06, 0xd3, 0xc1, 0x6c, 0x94, 0x39, 0x9d, 0xde, 0x01, 0xac, 0x88, 0x9a, 0x95, 0xe0, 0x85, 0xd0,
	0x36, 0x51, 0xf3, 0xea, 0x2b, 0x61, 0x35, 0x9e, 0xc1, 0xbe, 0xe1, 0xb2, 0x15, 0xc9, 0x9e, 0x33,
	0x3d, 0xa4, 0xef, 0x70, 0x68, 0x7b, 0x0f, 0x5c, 0x4a, 0x3c, 0x85, 0xa8, 0xd5, 0x32, 0x94, 0xac,
	0xc4, 0x73, 0x88, 0x2b, 0x41, 0xa5, 0x2a, 0x42, 0x29, 0x90, 0xfd, 0x7e, 0xae, 0x8a, 0x2e, 0x89,
	0x7a, 0xf7, 0x28, 0x73, 0x1a, 0x6f, 0xe1, 0xa0, 0x74, 0x7f, 0xdf, 0x25, 0xc3, 0x69, 0x34, 0x1b,
	0x2f, 0x2f, 0xd8, 0xaf, 0xa5, 0xd8, 0xf7, 0x0b, 0xb3, 0xcf, 0xec, 0xf2, 0x19, 0xe2, 0x47, 0x17,
	0xc0, 0x27, 0x00, 0xaf, 0xec, 0xa6, 0x78, 0xf9, 0xa7, 0xfd, 0xe3, 0x1e, 0x93, 0xc9, 0x3f, 0xd3,
	0xfe, 0x3c, 0x79, 0xec, 0x4e, 0x7a, 0xf3, 0x11, 0x00, 0x00, 0xff, 0xff, 0x1a, 0xbf, 0x5e, 0xee,
	0x95, 0x01, 0x00, 0x00,
}
