{
    "Parameters": {
        "Protoplast_movement_overlay1": {
            "OutPlatetype":"pcrplate_skirted_riser",
			"OutPlatetype2":"Nuncon12well_incubator",
			"AgarPlate":"falcon6wellAgar",
            "Cells":"protoplasts",
			"DNA":"dna_part",
			"PEG":"PEG",
			"Partname":"thepart",
			"CellVol":"10ul",
			"DNAVol":"2ul",
			"PEGVol":"190ul",
			"Plateoutvolume":"100ul",
			"TransformedCellsVol":"190ul",
			"OutWell":"A1",
			"OutWell2":"A1",
      "OutWell3":"A1"
        },"Protoplast_movement_overlay2": {
            "OutPlatetype":"pcrplate_skirted_riser",
			"OutPlatetype2":"Nuncon12well_incubator",
			"AgarPlate":"falcon6wellAgar",
            "Cells":"protoplasts",
			"DNA":"dna_part",
			"PEG":"PEG",
			"Partname":"thepart",
			"CellVol":"10ul",
			"DNAVol":"2ul",
			"PEGVol":"190ul",
			"Plateoutvolume":"100ul",
			"TransformedCellsVol":"190ul",
			"OutWell":"A2",
			"OutWell2":"A2",
      "OutWell3":"A2"
        }, "Protoplast_movement_overlay3": {
            "OutPlatetype":"pcrplate_skirted_riser",
            "OutPlatetype2":"Nuncon12well_incubator",
            "AgarPlate":"falcon6wellAgar",
            "Cells":"protoplasts",
            "DNA":"dna_part",
            "PEG":"PEG",
            "Partname":"thepart",
            "CellVol":"10ul",
            "DNAVol":"2ul",
            "PEGVol":"190ul",
            "Plateoutvolume":"100ul",
            "TransformedCellsVol":"190ul",
            "OutWell":"A3",
            "OutWell2":"A3",
      "OutWell3":"A3"
        }, "Protoplast_movement_overlay4": {
            "OutPlatetype":"pcrplate_skirted_riser",
            "OutPlatetype2":"Nuncon12well_incubator",
            "AgarPlate":"falcon6wellAgar",
            "Cells":"protoplasts",
            "DNA":"dna_part",
            "PEG":"PEG",
            "Partname":"thepart",
            "CellVol":"10ul",
            "DNAVol":"2ul",
            "PEGVol":"190ul",
            "Plateoutvolume":"100ul",
            "TransformedCellsVol":"190ul",
            "OutWell":"A4",
            "OutWell2":"A4",
      "OutWell3":"B1"
        }
    }
}
