// Code generated by protoc-gen-go.
// source: github.com/antha-lang/antha/driver/antha_shakerincubator_v1/shakerincubator.proto
// DO NOT EDIT!

/*
Package antha_shakerincubator_v1 is a generated protocol buffer package.

It is generated from these files:
	github.com/antha-lang/antha/driver/antha_shakerincubator_v1/shakerincubator.proto

It has these top-level messages:
	BoolReply
	ShakerSettings
	TemperatureSettings
	Blank
*/
package antha_shakerincubator_v1

import proto "github.com/antha-lang/antha/bvendor/github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import antha_driver_v1 "github.com/antha-lang/antha/driver/antha_driver_v1"

import (
	context "github.com/antha-lang/antha/bvendor/golang.org/x/net/context"
	grpc "github.com/antha-lang/antha/bvendor/google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type BoolReply struct {
	Result bool `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *BoolReply) Reset()                    { *m = BoolReply{} }
func (m *BoolReply) String() string            { return proto.CompactTextString(m) }
func (*BoolReply) ProtoMessage()               {}
func (*BoolReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ShakerSettings struct {
	Frequency float64 `protobuf:"fixed64,1,opt,name=frequency" json:"frequency,omitempty"`
	Radius    float64 `protobuf:"fixed64,2,opt,name=radius" json:"radius,omitempty"`
}

func (m *ShakerSettings) Reset()                    { *m = ShakerSettings{} }
func (m *ShakerSettings) String() string            { return proto.CompactTextString(m) }
func (*ShakerSettings) ProtoMessage()               {}
func (*ShakerSettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type TemperatureSettings struct {
	Temperature float64 `protobuf:"fixed64,1,opt,name=temperature" json:"temperature,omitempty"`
}

func (m *TemperatureSettings) Reset()                    { *m = TemperatureSettings{} }
func (m *TemperatureSettings) String() string            { return proto.CompactTextString(m) }
func (*TemperatureSettings) ProtoMessage()               {}
func (*TemperatureSettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Blank struct {
}

func (m *Blank) Reset()                    { *m = Blank{} }
func (m *Blank) String() string            { return proto.CompactTextString(m) }
func (*Blank) ProtoMessage()               {}
func (*Blank) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*BoolReply)(nil), "antha.shakerincubator.v1.BoolReply")
	proto.RegisterType((*ShakerSettings)(nil), "antha.shakerincubator.v1.ShakerSettings")
	proto.RegisterType((*TemperatureSettings)(nil), "antha.shakerincubator.v1.TemperatureSettings")
	proto.RegisterType((*Blank)(nil), "antha.shakerincubator.v1.Blank")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for ShakerIncubator service

type ShakerIncubatorClient interface {
	Connect(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BoolReply, error)
	Disconnect(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BoolReply, error)
	Test(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BoolReply, error)
	CarrierOpen(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BoolReply, error)
	CarrierClose(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BoolReply, error)
	ShakeStart(ctx context.Context, in *ShakerSettings, opts ...grpc.CallOption) (*BoolReply, error)
	ShakeStop(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BoolReply, error)
	TemperatureSet(ctx context.Context, in *TemperatureSettings, opts ...grpc.CallOption) (*BoolReply, error)
	TemperatureReset(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BoolReply, error)
	DriverType(ctx context.Context, in *antha_driver_v1.TypeRequest, opts ...grpc.CallOption) (*antha_driver_v1.TypeReply, error)
}

type shakerIncubatorClient struct {
	cc *grpc.ClientConn
}

func NewShakerIncubatorClient(cc *grpc.ClientConn) ShakerIncubatorClient {
	return &shakerIncubatorClient{cc}
}

func (c *shakerIncubatorClient) Connect(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := grpc.Invoke(ctx, "/antha.shakerincubator.v1.ShakerIncubator/Connect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shakerIncubatorClient) Disconnect(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := grpc.Invoke(ctx, "/antha.shakerincubator.v1.ShakerIncubator/Disconnect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shakerIncubatorClient) Test(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := grpc.Invoke(ctx, "/antha.shakerincubator.v1.ShakerIncubator/Test", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shakerIncubatorClient) CarrierOpen(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := grpc.Invoke(ctx, "/antha.shakerincubator.v1.ShakerIncubator/CarrierOpen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shakerIncubatorClient) CarrierClose(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := grpc.Invoke(ctx, "/antha.shakerincubator.v1.ShakerIncubator/CarrierClose", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shakerIncubatorClient) ShakeStart(ctx context.Context, in *ShakerSettings, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := grpc.Invoke(ctx, "/antha.shakerincubator.v1.ShakerIncubator/ShakeStart", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shakerIncubatorClient) ShakeStop(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := grpc.Invoke(ctx, "/antha.shakerincubator.v1.ShakerIncubator/ShakeStop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shakerIncubatorClient) TemperatureSet(ctx context.Context, in *TemperatureSettings, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := grpc.Invoke(ctx, "/antha.shakerincubator.v1.ShakerIncubator/TemperatureSet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shakerIncubatorClient) TemperatureReset(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := grpc.Invoke(ctx, "/antha.shakerincubator.v1.ShakerIncubator/TemperatureReset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shakerIncubatorClient) DriverType(ctx context.Context, in *antha_driver_v1.TypeRequest, opts ...grpc.CallOption) (*antha_driver_v1.TypeReply, error) {
	out := new(antha_driver_v1.TypeReply)
	err := grpc.Invoke(ctx, "/antha.shakerincubator.v1.ShakerIncubator/DriverType", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShakerIncubator service

type ShakerIncubatorServer interface {
	Connect(context.Context, *Blank) (*BoolReply, error)
	Disconnect(context.Context, *Blank) (*BoolReply, error)
	Test(context.Context, *Blank) (*BoolReply, error)
	CarrierOpen(context.Context, *Blank) (*BoolReply, error)
	CarrierClose(context.Context, *Blank) (*BoolReply, error)
	ShakeStart(context.Context, *ShakerSettings) (*BoolReply, error)
	ShakeStop(context.Context, *Blank) (*BoolReply, error)
	TemperatureSet(context.Context, *TemperatureSettings) (*BoolReply, error)
	TemperatureReset(context.Context, *Blank) (*BoolReply, error)
	DriverType(context.Context, *antha_driver_v1.TypeRequest) (*antha_driver_v1.TypeReply, error)
}

func RegisterShakerIncubatorServer(s *grpc.Server, srv ShakerIncubatorServer) {
	s.RegisterService(&_ShakerIncubator_serviceDesc, srv)
}

func _ShakerIncubator_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Blank)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ShakerIncubatorServer).Connect(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ShakerIncubator_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Blank)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ShakerIncubatorServer).Disconnect(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ShakerIncubator_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Blank)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ShakerIncubatorServer).Test(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ShakerIncubator_CarrierOpen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Blank)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ShakerIncubatorServer).CarrierOpen(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ShakerIncubator_CarrierClose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Blank)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ShakerIncubatorServer).CarrierClose(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ShakerIncubator_ShakeStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ShakerSettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ShakerIncubatorServer).ShakeStart(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ShakerIncubator_ShakeStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Blank)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ShakerIncubatorServer).ShakeStop(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ShakerIncubator_TemperatureSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(TemperatureSettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ShakerIncubatorServer).TemperatureSet(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ShakerIncubator_TemperatureReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Blank)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ShakerIncubatorServer).TemperatureReset(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ShakerIncubator_DriverType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(antha_driver_v1.TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ShakerIncubatorServer).DriverType(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _ShakerIncubator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "antha.shakerincubator.v1.ShakerIncubator",
	HandlerType: (*ShakerIncubatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _ShakerIncubator_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _ShakerIncubator_Disconnect_Handler,
		},
		{
			MethodName: "Test",
			Handler:    _ShakerIncubator_Test_Handler,
		},
		{
			MethodName: "CarrierOpen",
			Handler:    _ShakerIncubator_CarrierOpen_Handler,
		},
		{
			MethodName: "CarrierClose",
			Handler:    _ShakerIncubator_CarrierClose_Handler,
		},
		{
			MethodName: "ShakeStart",
			Handler:    _ShakerIncubator_ShakeStart_Handler,
		},
		{
			MethodName: "ShakeStop",
			Handler:    _ShakerIncubator_ShakeStop_Handler,
		},
		{
			MethodName: "TemperatureSet",
			Handler:    _ShakerIncubator_TemperatureSet_Handler,
		},
		{
			MethodName: "TemperatureReset",
			Handler:    _ShakerIncubator_TemperatureReset_Handler,
		},
		{
			MethodName: "DriverType",
			Handler:    _ShakerIncubator_DriverType_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x94, 0xcf, 0x6b, 0xe2, 0x40,
	0x14, 0xc7, 0xd7, 0x65, 0x57, 0xd7, 0xe7, 0x62, 0xcb, 0x14, 0x8a, 0x04, 0xa1, 0x12, 0x2f, 0x5e,
	0x8c, 0xd8, 0x1e, 0x7a, 0x2c, 0x68, 0x11, 0x7a, 0x69, 0x31, 0x49, 0x7b, 0x28, 0x14, 0x19, 0xe3,
	0x53, 0x83, 0x71, 0x26, 0x9d, 0x99, 0x08, 0xfe, 0xe9, 0xbd, 0x35, 0x4e, 0x62, 0xfd, 0x41, 0x53,
	0x3c, 0xe4, 0x36, 0xef, 0xd7, 0xe7, 0xbd, 0xbc, 0x7c, 0x67, 0x60, 0x38, 0xf3, 0xd5, 0x3c, 0x1a,
	0x5b, 0x1e, 0x5f, 0x76, 0x28, 0x53, 0x73, 0xda, 0x0e, 0x28, 0x9b, 0x25, 0xc7, 0xce, 0x44, 0xf8,
	0x2b, 0x14, 0x89, 0x31, 0x92, 0x73, 0xba, 0x40, 0xe1, 0x33, 0x2f, 0x1a, 0x53, 0xc5, 0xc5, 0x68,
	0xd5, 0xed, 0x1c, 0xb9, 0xac, 0x50, 0x70, 0xc5, 0x49, 0x4d, 0xe7, 0x5b, 0xc7, 0xc1, 0x55, 0xd7,
	0xb8, 0x3b, 0xb9, 0x59, 0x62, 0x6c, 0x7a, 0x24, 0xa7, 0x04, 0x6d, 0x36, 0xa1, 0xdc, 0xe3, 0x3c,
	0xb0, 0x31, 0x0c, 0xd6, 0xe4, 0x12, 0x8a, 0x02, 0x65, 0x14, 0xa8, 0x5a, 0xa1, 0x51, 0x68, 0xfd,
	0xb3, 0x53, 0xcb, 0x1c, 0x40, 0xd5, 0xd1, 0xbd, 0x1d, 0x54, 0xca, 0x67, 0x33, 0x49, 0xea, 0x50,
	0x9e, 0x0a, 0x7c, 0x8f, 0x90, 0x79, 0x6b, 0x9d, 0x5c, 0xb0, 0x77, 0x0e, 0xcd, 0xa1, 0x13, 0x3f,
	0x92, 0xb5, 0xdf, 0x3a, 0x94, 0x5a, 0xe6, 0x2d, 0x5c, 0xb8, 0xb8, 0x0c, 0x51, 0x50, 0x15, 0x09,
	0xfc, 0x82, 0x35, 0xa0, 0xa2, 0x76, 0xee, 0x14, 0xb7, 0xef, 0x32, 0x4b, 0xf0, 0xb7, 0x17, 0x7f,
	0xd8, 0xe2, 0xfa, 0xa3, 0x08, 0x67, 0xc9, 0x28, 0x0f, 0xdb, 0x35, 0x90, 0x21, 0x94, 0xfa, 0x9c,
	0x31, 0xf4, 0x14, 0xb9, 0xb2, 0xb2, 0x36, 0x65, 0xe9, 0x7a, 0xa3, 0xf9, 0x43, 0xc2, 0x76, 0x0d,
	0xe6, 0x2f, 0xe2, 0x02, 0xdc, 0xfb, 0xd2, 0xcb, 0x99, 0xfa, 0x08, 0x7f, 0x5c, 0x94, 0xf9, 0xf1,
	0x9e, 0xa1, 0xd2, 0xa7, 0x42, 0xf8, 0x28, 0x9e, 0x42, 0x64, 0xb9, 0x61, 0x5f, 0xe0, 0x7f, 0x8a,
	0xed, 0x07, 0x5c, 0x62, 0x6e, 0xdc, 0x37, 0x00, 0xfd, 0xeb, 0x1c, 0x45, 0x85, 0x22, 0xad, 0xec,
	0xa2, 0x43, 0xad, 0x9d, 0x8a, 0x77, 0xa0, 0x9c, 0xe2, 0x79, 0x98, 0xdb, 0xcc, 0x53, 0xa8, 0x1e,
	0x2a, 0x96, 0xb4, 0xb3, 0x0b, 0xbf, 0xd1, 0xf6, 0xa9, 0x7d, 0x5e, 0xe1, 0x7c, 0xaf, 0xda, 0x46,
	0x89, 0xf9, 0xc9, 0x64, 0x10, 0x8b, 0x59, 0x5f, 0x79, 0x77, 0x1d, 0x22, 0xa9, 0xa7, 0x45, 0xe9,
	0x2b, 0xb0, 0x19, 0x3b, 0x76, 0xdb, 0x9b, 0xab, 0x2b, 0x95, 0x61, 0x64, 0x44, 0x63, 0xd2, 0xb8,
	0xa8, 0x5f, 0x8c, 0x9b, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x64, 0x4e, 0xea, 0x0d, 0xe1, 0x04,
	0x00, 0x00,
}
