// Code generated by protoc-gen-go.
// source: github.com/antha-lang/antha/driver/antha_runner_v1/runner.proto
// DO NOT EDIT!

/*
Package antha_runner_v1 is a generated protocol buffer package.

It is generated from these files:
	github.com/antha-lang/antha/driver/antha_runner_v1/runner.proto

It has these top-level messages:
	RunRequest
	RunRefRequest
	RunReply
	MessagesRequest
	MessagesReply
	SupportedRunTypesRequest
	SupportedRunTypesReply
*/
package antha_runner_v1

import proto "github.com/antha-lang/antha/bvendor/github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import antha_driver_v1 "github.com/antha-lang/antha/driver/antha_driver_v1"

import (
	context "github.com/antha-lang/antha/bvendor/golang.org/x/net/context"
	grpc "github.com/antha-lang/antha/bvendor/google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type RunRequest struct {
	Type string                    `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Data []byte                    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Done *antha_driver_v1.HttpCall `protobuf:"bytes,3,opt,name=done" json:"done,omitempty"`
}

func (m *RunRequest) Reset()                    { *m = RunRequest{} }
func (m *RunRequest) String() string            { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()               {}
func (*RunRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RunRequest) GetDone() *antha_driver_v1.HttpCall {
	if m != nil {
		return m.Done
	}
	return nil
}

type RunRefRequest struct {
	Type string                    `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Data *antha_driver_v1.HttpCall `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	Done *antha_driver_v1.HttpCall `protobuf:"bytes,3,opt,name=done" json:"done,omitempty"`
}

func (m *RunRefRequest) Reset()                    { *m = RunRefRequest{} }
func (m *RunRefRequest) String() string            { return proto.CompactTextString(m) }
func (*RunRefRequest) ProtoMessage()               {}
func (*RunRefRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RunRefRequest) GetData() *antha_driver_v1.HttpCall {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RunRefRequest) GetDone() *antha_driver_v1.HttpCall {
	if m != nil {
		return m.Done
	}
	return nil
}

type RunReply struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *RunReply) Reset()                    { *m = RunReply{} }
func (m *RunReply) String() string            { return proto.CompactTextString(m) }
func (*RunReply) ProtoMessage()               {}
func (*RunReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type MessagesRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *MessagesRequest) Reset()                    { *m = MessagesRequest{} }
func (m *MessagesRequest) String() string            { return proto.CompactTextString(m) }
func (*MessagesRequest) ProtoMessage()               {}
func (*MessagesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type MessagesReply struct {
	Values []*MessagesReply_Message `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *MessagesReply) Reset()                    { *m = MessagesReply{} }
func (m *MessagesReply) String() string            { return proto.CompactTextString(m) }
func (*MessagesReply) ProtoMessage()               {}
func (*MessagesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MessagesReply) GetValues() []*MessagesReply_Message {
	if m != nil {
		return m.Values
	}
	return nil
}

type MessagesReply_Message struct {
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Seq  int32  `protobuf:"varint,2,opt,name=seq" json:"seq,omitempty"`
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *MessagesReply_Message) Reset()                    { *m = MessagesReply_Message{} }
func (m *MessagesReply_Message) String() string            { return proto.CompactTextString(m) }
func (*MessagesReply_Message) ProtoMessage()               {}
func (*MessagesReply_Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type SupportedRunTypesRequest struct {
}

func (m *SupportedRunTypesRequest) Reset()                    { *m = SupportedRunTypesRequest{} }
func (m *SupportedRunTypesRequest) String() string            { return proto.CompactTextString(m) }
func (*SupportedRunTypesRequest) ProtoMessage()               {}
func (*SupportedRunTypesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type SupportedRunTypesReply struct {
	Types []string `protobuf:"bytes,1,rep,name=types" json:"types,omitempty"`
}

func (m *SupportedRunTypesReply) Reset()                    { *m = SupportedRunTypesReply{} }
func (m *SupportedRunTypesReply) String() string            { return proto.CompactTextString(m) }
func (*SupportedRunTypesReply) ProtoMessage()               {}
func (*SupportedRunTypesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*RunRequest)(nil), "antha.runner.v1.RunRequest")
	proto.RegisterType((*RunRefRequest)(nil), "antha.runner.v1.RunRefRequest")
	proto.RegisterType((*RunReply)(nil), "antha.runner.v1.RunReply")
	proto.RegisterType((*MessagesRequest)(nil), "antha.runner.v1.MessagesRequest")
	proto.RegisterType((*MessagesReply)(nil), "antha.runner.v1.MessagesReply")
	proto.RegisterType((*MessagesReply_Message)(nil), "antha.runner.v1.MessagesReply.Message")
	proto.RegisterType((*SupportedRunTypesRequest)(nil), "antha.runner.v1.SupportedRunTypesRequest")
	proto.RegisterType((*SupportedRunTypesReply)(nil), "antha.runner.v1.SupportedRunTypesReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Runner service

type RunnerClient interface {
	// Run a blob
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error)
	// Run a blob identified by reference
	// rpc RunRef(RunRefRequest) returns (RunReply);
	// Messages from run (call repeatedly to get more messages)
	Messages(ctx context.Context, in *MessagesRequest, opts ...grpc.CallOption) (*MessagesReply, error)
	// Types of files that can be run
	SupportedRunTypes(ctx context.Context, in *SupportedRunTypesRequest, opts ...grpc.CallOption) (*SupportedRunTypesReply, error)
}

type runnerClient struct {
	cc *grpc.ClientConn
}

func NewRunnerClient(cc *grpc.ClientConn) RunnerClient {
	return &runnerClient{cc}
}

func (c *runnerClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error) {
	out := new(RunReply)
	err := grpc.Invoke(ctx, "/antha.runner.v1.Runner/Run", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) Messages(ctx context.Context, in *MessagesRequest, opts ...grpc.CallOption) (*MessagesReply, error) {
	out := new(MessagesReply)
	err := grpc.Invoke(ctx, "/antha.runner.v1.Runner/Messages", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) SupportedRunTypes(ctx context.Context, in *SupportedRunTypesRequest, opts ...grpc.CallOption) (*SupportedRunTypesReply, error) {
	out := new(SupportedRunTypesReply)
	err := grpc.Invoke(ctx, "/antha.runner.v1.Runner/SupportedRunTypes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Runner service

type RunnerServer interface {
	// Run a blob
	Run(context.Context, *RunRequest) (*RunReply, error)
	// Run a blob identified by reference
	// rpc RunRef(RunRefRequest) returns (RunReply);
	// Messages from run (call repeatedly to get more messages)
	Messages(context.Context, *MessagesRequest) (*MessagesReply, error)
	// Types of files that can be run
	SupportedRunTypes(context.Context, *SupportedRunTypesRequest) (*SupportedRunTypesReply, error)
}

func RegisterRunnerServer(s *grpc.Server, srv RunnerServer) {
	s.RegisterService(&_Runner_serviceDesc, srv)
}

func _Runner_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RunnerServer).Run(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Runner_Messages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(MessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RunnerServer).Messages(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Runner_SupportedRunTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SupportedRunTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RunnerServer).SupportedRunTypes(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Runner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "antha.runner.v1.Runner",
	HandlerType: (*RunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Runner_Run_Handler,
		},
		{
			MethodName: "Messages",
			Handler:    _Runner_Messages_Handler,
		},
		{
			MethodName: "SupportedRunTypes",
			Handler:    _Runner_SupportedRunTypes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x53, 0x4b, 0x4f, 0xf2, 0x40,
	0x14, 0x4d, 0xe9, 0x07, 0x1f, 0x5c, 0x1f, 0xe8, 0xc4, 0x98, 0x52, 0x13, 0x83, 0x5d, 0xf8, 0x58,
	0x30, 0x04, 0x5c, 0xab, 0x0b, 0x36, 0x2e, 0x74, 0x33, 0xba, 0x27, 0x03, 0x1d, 0x0b, 0x49, 0x6d,
	0x4b, 0x3b, 0x6d, 0xc2, 0xd2, 0xff, 0xe0, 0xef, 0x35, 0xce, 0xa3, 0x05, 0x05, 0xac, 0xc4, 0xdd,
	0xb9, 0x77, 0xee, 0x9c, 0x7b, 0xce, 0x99, 0x16, 0xee, 0xbc, 0x29, 0x9f, 0xa4, 0x23, 0x3c, 0x0e,
	0x5f, 0xbb, 0x34, 0xe0, 0x13, 0xda, 0xf1, 0x69, 0xe0, 0x69, 0xd8, 0x75, 0xe3, 0x69, 0xc6, 0x62,
	0x5d, 0x0c, 0xe3, 0x34, 0x08, 0x58, 0x3c, 0xcc, 0x7a, 0x5d, 0x8d, 0x70, 0x14, 0x87, 0x3c, 0x44,
	0x4d, 0x75, 0x8a, 0xf3, 0x5e, 0xd6, 0xb3, 0xb7, 0x67, 0xd4, 0x85, 0x64, 0xd4, 0x48, 0x33, 0x3a,
	0x63, 0x00, 0x92, 0x06, 0x84, 0xcd, 0x52, 0x96, 0x70, 0x84, 0xe0, 0x1f, 0x9f, 0x47, 0xcc, 0x32,
	0xda, 0xc6, 0x65, 0x83, 0x28, 0x2c, 0x7b, 0x2e, 0xe5, 0xd4, 0xaa, 0x88, 0xde, 0x2e, 0x51, 0x18,
	0x75, 0x44, 0x2f, 0x0c, 0x98, 0x65, 0x8a, 0xde, 0x4e, 0xbf, 0x85, 0xb5, 0xac, 0x9c, 0x38, 0xeb,
	0xe1, 0x7b, 0xce, 0xa3, 0x01, 0xf5, 0x7d, 0xa2, 0xc6, 0x9c, 0x37, 0x03, 0xf6, 0xd4, 0x96, 0x97,
	0xb2, 0x45, 0x9d, 0x2f, 0x8b, 0x7e, 0x21, 0xfd, 0x83, 0x06, 0x1b, 0xea, 0x4a, 0x42, 0xe4, 0xcf,
	0xd1, 0x3e, 0x54, 0xa6, 0x6e, 0xbe, 0x5b, 0x20, 0xe7, 0x0c, 0x9a, 0x8f, 0x2c, 0x49, 0xa8, 0xc7,
	0x92, 0x42, 0xe0, 0xea, 0xc8, 0xbb, 0xb0, 0xb0, 0x9c, 0x91, 0x24, 0xb7, 0x50, 0xcb, 0xa8, 0x2f,
	0x86, 0xc5, 0x94, 0x29, 0x14, 0x9c, 0xe3, 0x95, 0xc7, 0xc1, 0xdf, 0xe6, 0x8b, 0x8a, 0xe4, 0xb7,
	0xec, 0x01, 0xfc, 0xcf, 0x5b, 0x32, 0x8d, 0x71, 0xe8, 0x2e, 0xd2, 0x90, 0x18, 0x1d, 0x80, 0x99,
	0xb0, 0x99, 0x0a, 0xa3, 0x4a, 0x24, 0x5c, 0x3c, 0x84, 0xb9, 0x7c, 0x08, 0xe1, 0xca, 0x7a, 0x4a,
	0xa3, 0x28, 0x8c, 0x39, 0x73, 0x85, 0xbd, 0x67, 0x91, 0x63, 0x61, 0xc1, 0xc1, 0x70, 0xbc, 0xe1,
	0x4c, 0x4a, 0x3f, 0x82, 0xaa, 0x4c, 0x5c, 0x2b, 0x6f, 0x10, 0x5d, 0xf4, 0x3f, 0x0c, 0xa8, 0x11,
	0x25, 0x1e, 0xdd, 0x80, 0x29, 0x10, 0x3a, 0x59, 0xb3, 0xb4, 0xfc, 0x56, 0xec, 0xd6, 0xe6, 0x43,
	0xc9, 0xff, 0x00, 0xf5, 0xc2, 0x3b, 0x6a, 0x97, 0xc4, 0xa2, 0x89, 0x4e, 0xcb, 0x83, 0x43, 0x1e,
	0x1c, 0xae, 0xf9, 0x40, 0x57, 0x6b, 0x97, 0x7e, 0xca, 0xc1, 0xbe, 0xd8, 0x66, 0x54, 0x2c, 0x1a,
	0xd5, 0xd4, 0x2f, 0x71, 0xfd, 0x19, 0x00, 0x00, 0xff, 0xff, 0x70, 0x7c, 0x77, 0x85, 0xa7, 0x03,
	0x00, 0x00,
}
